config/routes.rb
DentistrySite::Application.routes.draw do
  get "rails/home"
  get "rails/success"
  get "rails/view"

  resources :patients

  root 'patients#new'

end

app/models/patient.rb
class Patient < ActiveRecord::Base

	has_attached_file :avatar, 
	:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
	:url => "/system/:attachment/:id/:basename_:style.:extension",
	:storage => :s3,
	:bucket => 'dentistrysg',
	:s3_credentials => {
		    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
		},
	:styles => {
	  :thumb    => ['100x100#',  :jpg, :quality => 70],
	  :preview  => ['480x480#',  :jpg, :quality => 70],
	  :large    => ['600>',      :jpg, :quality => 70],
	  :retina   => ['1200>',     :jpg, :quality => 30]
	},
	:convert_options => {
	  :thumb    => '-set colorspace sRGB -strip',
	  :preview  => '-set colorspace sRGB -strip',
	  :large    => '-set colorspace sRGB -strip',
	  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
	}
	do_not_validate_attachment_file_type :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	require 'digest/sha1' 
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :logged_in?

	def logged_in?
	  session[:login]
	end

	private
	def authenticate
	  login = authenticate_or_request_with_http_basic do |username, password|
		username == APP_CONFIG['username'] && Digest::SHA1.hexdigest(password) == APP_CONFIG['password']

	  end
	  session[:login] = login
	end

	def do_logout
	  session[:login] = nil
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def success
  end

  def view
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

	before_filter :authenticate, :except => [:new, :create, :show]

	def index
   		@patients = Patient.all
  	end

	def show
		@patients = Patient.find(params[:id])
	end

	def new
		@patients = Patient.new
	end

	def create
		@patients = Patient.new(params.require(:patient).permit(:name, :number, :email, :appointment, :description, :avatar))

		@patients.save
		redirect_to @patients
	end
	def destroy
		@patients = Patient.find(params[:id])
		@patients.destroy

		redirect_to :back
	end
end

app/controllers/rails_controller.rb
class RailsController < ApplicationController
  def home
  end

  def success
  end

  def view
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dentistry Site</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header>
      
       
          <%= link_to "DentalNow", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '/patients/new' %></li>
            </ul>
          </nav>
       
     
    </header>

      <%= yield %>
<footer></footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/success.html.erb
<h1>Pages#success</h1>
<p>Find me in app/views/pages/success.html.erb</p>

app/views/pages/view.html.erb
<h1>Pages#view</h1>
<p>Find me in app/views/pages/view.html.erb</p>

app/views/patients/index.html.erb
<h1>Listing patients</h1>
 
<table class = "table">
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th>Email</th>
    <th>Current Appointment</th>
    <th>Description</th>
    <th>Dental Image</th>
    <th>Remove</th>
  </tr>
 
  <% @patients.each do |patients| %>
    <tr>
      <td><%= patients.name %></td>
      <td><%= patients.number %></td>
      <td><%= patients.email %></td>
      <td><%= patients.appointment %></td>
      <td><%= patients.description %></td>
      <td><%= image_tag patients.avatar.url(:thumb) %></td>
      <td><%= link_to 'Delete', patient_path(patients),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/patients/new.html.erb
<section id="splash">
		<div class = "title">
			<h1 id="mainh1">Dental Now</h1>
			<h2 id="mainh2">
			You don't have to wait for good teeth.
			</h2>
		</div>


					<div class="morph-button morph-button-modal morph-button-modal-3 morph-button-fixed">
						<button type="button" class="butt">Sign-up now</button>
						<div class="morph-content">
							<div>
								<div class="content-style-form content-style-form-2">
									<span class="icon-close"></span>
									<h2 id ="signup">Sign-Up</h2>
								
									<%= form_for @patients do |f| %>
										<div class = "form-group">
											<%= f.text_field :name, :class => "form-input", :placeholder => "Name"%>
										</div>
										<div class = "form-group">
											<%= f.text_field :number, :class => "form-input", :placeholder => "Number"%>
										</div>
										<div class = "form-group">
											<%= f.text_field :email, :class => "form-input", :placeholder => "hello@mail.com"%>
										</div>
										<div class = "form-group">
											<%=f.date_field :appointment, :class => "form-input", :placeholder => "placeholder text"%>
										</div>
										<div class = "form-group">
											<%=f.label :avatar, "Dental Images (optional)", :class => "form-label" %>
											<%=f.file_field :avatar, :class => "form-input" %>
											<p class = "prompt">Please take a clearly visible picture of your teeth with the relevant problem</p>
										</div>
										<div class = "form-group">
											<%= f.label :description, "Please Describe your Symptoms", :class => "form-label" %>
											<%= f.text_area :description, size: "60x6", :class => "form-input" %>
										</div>
										<p>
											<%= f.submit "Submit", class: "btn btn-primary" %>
										</p>
									<% end %>
									
								</div>
							</div>
						</div>
					</div><!-- morph-button -->
				</div><!-- /form-mockup -->
			</section>
<section id="about">
<h3>About Us</h3>
<p>
We are dentists too.
</p>
<div id="iconwrap" class="clearfix">
	<div class="icons moolah">
	  <a class="first-link" href="">
	   
	  </a>
	  <a class="second" href="">
	    Cheap ($30 bux vs. $300)
	  </a>
	</div>
	<div class="icons time">
	  <a class="first-link" href="">
	    
	  </a>
	  <a class="second" href="">
	   Current waiting time of 2 weeks compared to 3 - 6 months for public dental care
	  </a>
	</div>
	<div class="icons quality">
	  <a class="first-link" href="">
	   
	  </a>
	  <a class="second" href="">
	    Supervised by specialists with average x years of experience
	  </a>
	</div>
</div>
</section>
			<section id="contact">
				<h3>Contact Us</h3>

				<p>You may email us at: <a href="mailto:zhangyitao91@gmail.com?subject=hello">zhangyitao91@gmail.com</a></p>
				<p>or call us at <a href="tel://">+65 9777 7777</a>
				</p>
				<p></p>
			</section>
		
		<script src="js/classie.js"></script>
		<script src="js/uiMorphingButton_fixed.js"></script>
		<script>
			(function() {
				var docElem = window.document.documentElement, didScroll, scrollPosition;

				// trick to prevent scrolling when opening/closing button
				function noScrollFn() {
					window.scrollTo( scrollPosition ? scrollPosition.x : 0, scrollPosition ? scrollPosition.y : 0 );
				}

				function noScroll() {
					window.removeEventListener( 'scroll', scrollHandler );
					window.addEventListener( 'scroll', noScrollFn );
				}

				function scrollFn() {
					window.addEventListener( 'scroll', scrollHandler );
				}

				function canScroll() {
					window.removeEventListener( 'scroll', noScrollFn );
					scrollFn();
				}

				function scrollHandler() {
					if( !didScroll ) {
						didScroll = true;
						setTimeout( function() { scrollPage(); }, 60 );
					}
				};

				function scrollPage() {
					scrollPosition = { x : window.pageXOffset || docElem.scrollLeft, y : window.pageYOffset || docElem.scrollTop };
					didScroll = false;
				};

				scrollFn();

				[].slice.call( document.querySelectorAll( '.morph-button' ) ).forEach( function( bttn ) {
					new UIMorphingButton( bttn, {
						closeEl : '.icon-close',
						onBeforeOpen : function() {
							// don't allow to scroll
							noScroll();
						},
						onAfterOpen : function() {
							// can scroll again
							canScroll();
						},
						onBeforeClose : function() {
							// don't allow to scroll
							noScroll();
						},
						onAfterClose : function() {
							// can scroll again
							canScroll();
						}
					} );
				} );

				// for demo purposes only
				[].slice.call( document.querySelectorAll( 'form button' ) ).forEach( function( bttn ) { 
					bttn.addEventListener( 'click', function( ev ) { ev.preventDefault(); } );
				} );
			})();
		</script>

app/views/patients/show.html.erb
<h1> Thank you for your submission </h1>

<table class = "table">
	<tr>
	<th>Name</th>
	<th>Number</th>
	<th>Email</th>
	<th>Current Appointment</th>
	<th>Description</th>
	<th>Dental Image</th>
	</tr>

	<tr>
	  <td><%= @patients.name %></td>
	  <td><%= @patients.number %></td>
	  <td><%= @patients.email %></td>
	  <td><%= @patients.appointment %></td>
	  <td><%= @patients.description %></td>
	  <td><%= image_tag @patients.avatar.url(:thumb) %></td>
	</tr>

</table>

app/views/rails/home.html.erb
<div class="center hero-unit">
  <h1>Dental Now</h1>

  <h2>
  Skip the dental waiting line!
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/rails/success.html.erb
<h1>Rails#success</h1>
<p>Find me in app/views/rails/success.html.erb</p>

app/views/rails/view.html.erb
<h1>Rails#view</h1>
<p>Find me in app/views/rails/view.html.erb</p>